name: Virtualization information

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Install virtualization tools
      run: apt-get update && apt-get install libvirt-clients
    - name: Check virtualization capabitilies
    - run: virt-host-validate
